version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: psm-be-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: psm-manager

    ports:
      - '5450:5432'

    volumes:
      - postgres-data:/var/lib/postgresql/data/

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d psm-manager"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7-alpine
    container_name: psm-be-redis
    restart: unless-stopped

    ports:
      - '6379:6379'

    volumes:
      - redis-data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  # rabbitmq:
  #   image: rabbitmq:4.0.9-management-alpine
  #   container_name: psm-rabbit-mq
  #   restart: unless-stopped
  #   ports: 
  #     - "5672:5672"    # AMQP
  #     - "15672:15672"  # Web UI
  #   volumes:
  #     - rabbitmq-data:/data
  #   healthcheck:
  #     test: ["CMD", "rabbitmq-diagnostics", "check_running"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
    

volumes:
  postgres-data:
  redis-data:
  rabbitmq-data:
